{
 "title": "Udacity Trial App - Frontend & Backend Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Jaeger homepage traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "operation": "homepage", "service": "backend-app" }
   ]
  },
  {
   "title": "Example jaeger homepage trace",
   "type": "traces",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "query": "745a9067e11dc050" }
   ]
  },
  {
   "title": "Frontend Uptime (minutes)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (pod) (time() - kube_pod_start_time{pod=~\"frontend-app.*\"}) / 60",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "Backend Uptime (minutes)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by (pod) (time() - kube_pod_start_time{pod=~\"backend-app.*\"}) / 60",
     "legendFormat": "backend"
    }
   ]
  },
  {
   "title": "Frontend 4xx Errors (24h)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{service='frontend-service', status=~'40.'}[24h])",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Frontend 5xx Errors (24h)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{service='frontend-service', status=~'50.'}[24h])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Backend 4xx Errors (24h)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{service='backend-service', status=~'40.'}[24h])",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Backend 5xx Errors (24h)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{service='backend-service', status=~'50.'}[24h])",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}